version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-api
    hostname: mongodb
    ports:
      - "27017:27017"
  mgm:
    build: ./.
    ports:
      - 8080:8080
    links:
      - mongodb
